version: "3"

services:
  server:
    build: backend/
    command: node app.js
    ports:
      - 3030:3030

  postgres:
    image: postgres:14.8-alpine3.18
    environment:
      POSTGRES_DB: ${PS_DB_NAME}
      POSTGRES_USER: ${PS_DB_USER}
      POSTGRES_PASSWORD: ${PS_DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/migrations:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$PS_DB_USER -d $$PS_DB_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  db-data: