version: "3"
services:
  server:
    build: .
    # Команда, которую нужно запустить после создания образа.
    # Следующая команда означает запуск "python ./server.py".
    command: node app.js
    ports:
      - 3030:3030
